name: cmake

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run : |
        cmake -S . -B build
        cmake --build build 

    - name: Test
      run : |
        cd build
        ./test --gtest_repeat=1000

